-- 동일한 회원이 동일한 상품을 재구매한 데이터에 대해
-- 재구매한 회원ID와 상품ID 출력
-- 회원ID 오름차순, 상품ID 내림차순
SELECT USER_ID, PRODUCT_ID
FROM ONLINE_SALE
GROUP BY USER_ID, PRODUCT_ID
HAVING COUNT(SALES_AMOUNT) > 1
ORDER BY USER_ID ASC, PRODUCT_ID DESC