-- PRODUCT 테이블과 OFFLINE_SALE 테이블에서
-- 상품코드 별 매출액(판매가 * 판매량) 합계를 출력하는 SQL문 작성
-- 결과는 매출액 기준 내림차순 정렬, 매출액 동일하면 상품코드를 기준으로 오름차순 정렬
SELECT P.PRODUCT_CODE, (P.PRICE * O.SALES_AMOUNT) AS 'SALES'
FROM PRODUCT P JOIN (
        SELECT PRODUCT_ID, SUM(SALES_AMOUNT) AS 'SALES_AMOUNT'
        FROM OFFLINE_SALE
        GROUP BY PRODUCT_ID
    ) O
ON P.PRODUCT_ID = O.PRODUCT_ID
ORDER BY (P.PRICE * O.SALES_AMOUNT) DESC, P.PRODUCT_CODE ASC;