-- CAR_RENTAL_COMPANY_CAR : 자동차 대여 회사에서 대여 중인 자동차들의 정보
-- CAR_RENTAL_COMPANY_RENTAL_HISTORY : 자동차 대여 기록
-- CAR_RENTAL_COMPANY_DISCOUNT_PLAN : 자동차 종류 별 대여 기간 및 할인 정책 정보
-- 자동차 종류가 '세단' 또는 'SUV'
-- 2022년 11월 1일부터 2022년 11월 30일까지
-- 30일간의 대여 금액이 50만원 이상, 200만원 미만
-- 대여 금액 내림차순, 자동차 종류 오름차순, 자동차 ID 내림차순


WITH DISCOUNT AS (
    SELECT CAR_TYPE, (1 - (DISCOUNT_RATE * 0.01)) AS RATE
    FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
    WHERE DURATION_TYPE='30일 이상'
)

SELECT C.CAR_ID,
       C.CAR_TYPE,
       ROUND(C.DAILY_FEE * D.RATE * 30) AS FEE
FROM CAR_RENTAL_COMPANY_CAR C
INNER JOIN DISCOUNT D
ON C.CAR_TYPE=D.CAR_TYPE
WHERE C.CAR_ID NOT IN (
        SELECT DISTINCT CAR_ID
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
        WHERE END_DATE > '2022-11-01'
)
AND C.CAR_TYPE IN ('SUV', '세단')
AND (C.DAILY_FEE * D.RATE * 30) >= 500000
AND (C.DAILY_FEE * D.RATE * 30) < 2000000
ORDER BY FEE DESC, C.CAR_TYPE ASC, C.CAR_ID DESC

