-- 식당의 정보 REST_INFO
-- 음식 종류별, 즐겨찾기수가 많은 식당
-- 음식 종류를 기준으로 내림차순
SELECT FOOD_TYPE, REST_ID, REST_NAME, FAVORITES
FROM REST_INFO
WHERE (FOOD_TYPE, FAVORITES) IN 
(
    SELECT FOOD_TYPE,
           MAX(FAVORITES) AS MAX_FAVORITES
    FROM REST_INFO
    GROUP BY FOOD_TYPE
)
ORDER BY FOOD_TYPE DESC