-- FOOD_PRODUCT : 식품의 정보
-- FOOD_ORDER : 테이블과 식품의 주문 정보
-- 생산일자가 2022년 05월
-- 총매출 내림차순, 식품ID 오름차순

SELECT FP.PRODUCT_ID, FP.PRODUCT_NAME, (FP.PRICE * SUB.TOTAL) AS TOTAL_SALES
FROM FOOD_PRODUCT FP
INNER JOIN (
              SELECT PRODUCT_ID, SUM(AMOUNT) AS TOTAL
              FROM FOOD_ORDER
              WHERE DATE_FORMAT(PRODUCE_DATE, '%Y-%m')='2022-05'
              GROUP BY PRODUCT_ID
           ) AS SUB
ON FP.PRODUCT_ID=SUB.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, FP.PRODUCT_ID ASC
