-- 중고 거래 게시판 정보를 담은 USED_GOODS_BOARD
-- 중고 거래 게시판 사용자 정보를 담은 USED_GOODS_USER
-- 완료된 중고 거래의 총 금액이 70만원 이상인 사람의 회원ID, 닉네임, 총거래금액 조회
SELECT B.WRITER_ID, U.NICKNAME, SUM(B.PRICE) AS TOTAL_SALES
FROM USED_GOODS_BOARD B
INNER JOIN USED_GOODS_USER U
ON B.WRITER_ID=U.USER_ID
WHERE STATUS='DONE'
GROUP BY B.WRITER_ID
HAVING SUM(B.PRICE) >= 700000
ORDER BY TOTAL_SALES ASC