-- MEMBER_PROFILE : 고객의 정보
-- REST_REVIEW : 테이블과 식당 리뷰 정보
-- 리뷰를 가장 많이 작성한 회원들의 리뷰 조회
SELECT MP.MEMBER_NAME, RR.REVIEW_TEXT, DATE_FORMAT(RR.REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
FROM MEMBER_PROFILE MP
INNER JOIN REST_REVIEW RR
INNER JOIN (
            SELECT MEMBER_ID, COUNT(*) AS TOTAL
            FROM REST_REVIEW
            GROUP BY MEMBER_ID
            ORDER BY TOTAL DESC
            LIMIT 1
          ) AS SUB
ON MP.MEMBER_ID=RR.MEMBER_ID AND RR.MEMBER_ID=SUB.MEMBER_ID
ORDER BY REVIEW_DATE ASC, RR.REVIEW_TEXT ASC