-- MEMBER_PROFILE : 고객의 정보
-- REST_REVIEW : 테이블과 식당 리뷰 정보
-- 리뷰를 가장 많이 작성한 회원들의 리뷰 조회
SELECT MP.MEMBER_NAME, RR.REVIEW_TEXT, DATE_FORMAT(RR.REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
FROM MEMBER_PROFILE MP
INNER JOIN REST_REVIEW RR
ON MP.MEMBER_ID=RR.MEMBER_ID
WHERE RR.MEMBER_ID = (
            SELECT MEMBER_ID
            FROM REST_REVIEW
            GROUP BY MEMBER_ID
            ORDER BY COUNT(*) DESC
            LIMIT 1
          )
ORDER BY REVIEW_DATE ASC, RR.REVIEW_TEXT ASC
