SELECT YEAR(ED.DIFFERENTIATION_DATE) AS YEAR,
       ABS(ED2.MAX_COLONY - ED.SIZE_OF_COLONY) AS YEAR_DEV,
       ID
FROM ECOLI_DATA ED
INNER JOIN (
            SELECT YEAR(DIFFERENTIATION_DATE) AS 'YEAR',
                   MAX(SIZE_OF_COLONY) AS 'MAX_COLONY'
            FROM ECOLI_DATA
            GROUP BY YEAR(DIFFERENTIATION_DATE)
           ) AS ED2
ON YEAR(ED.DIFFERENTIATION_DATE) = ED2.YEAR
ORDER BY YEAR ASC, YEAR_DEV ASC