-- 상반기 아이스크림 총 주문량이 3,000보다 높아
-- 아이스크림 주 성분이 과일
-- 총주문량이 큰 순서대로 조회
SELECT FH.FLAVOR
FROM FIRST_HALF FH
INNER JOIN ICECREAM_INFO IC
ON FH.FLAVOR=IC.FLAVOR
WHERE FH.TOTAL_ORDER > 3000
AND IC.INGREDIENT_TYPE='fruit_based'
ORDER BY FH.TOTAL_ORDER DESC 
