-- USED_GOODS_BOARD 테이블 : 중고거래 게시판 정보
-- USED_GOODS_REPLY 테이블 : 중고거래 게시판 첨부파일 정보
-- 2022년 10월에 작성된 게시글 제목, 게시글 ID, 댓글 ID, 댓글 작성자 ID, 댓글 내용, 댓글 작성일 조회
-- 댓글 작성일을 기준으로 오름차순, 게시글 제목을 기준으로 오름차순
SELECT UGB.TITLE, UGB.BOARD_ID, UGR.REPLY_ID, UGR.WRITER_ID, UGR.CONTENTS, DATE_FORMAT(UGR.CREATED_DATE, '%Y-%m-%d')
FROM USED_GOODS_BOARD UGB
INNER JOIN USED_GOODS_REPLY UGR
ON UGB.BOARD_ID=UGR.BOARD_ID
WHERE YEAR(UGB.CREATED_DATE)=2022
AND MONTH(UGB.CREATED_DATE)=10
ORDER BY UGR.CREATED_DATE ASC, UGB.TITLE ASC
