-- 2022년 1월, 카테고리 별 도서 판매량 합산
-- 카테고리, 총 판매량 리스트 출력
-- 카테고리 명을 기준으로 오름차순 정렬
SELECT B.CATEGORY, SUM(BS.SALES) AS 'TOTAL_SALES'
FROM BOOK B INNER JOIN BOOK_SALES BS
ON B.BOOK_ID = BS.BOOK_ID
WHERE YEAR(BS.SALES_DATE)='2022' AND MONTH(BS.SALES_DATE)='01'
GROUP BY B.CATEGORY
ORDER BY B.CATEGORY ASC;