-- 한 서점에서 판매중인 도서들의 도서 정보 BOOK, 판매 정보 BOOK_SALES
-- 2022년 1월, 카테고리 별 도서 판매량
-- 카테고리명을 기준으로 오름차순
SELECT B.CATEGORY, SUM(S.SALES) AS TOTAL_SALES
FROM BOOK_SALES S
INNER JOIN BOOK B
ON S.BOOK_ID=B.BOOK_ID
WHERE DATE_FORMAT(S.SALES_DATE, '%Y-%m')='2022-01'
GROUP BY B.CATEGORY
ORDER BY B.CATEGORY ASC
