-- 1. '경제' 카테고리에 속하는 도서 ID를 뽑늗다
-- 2. 
SELECT B.BOOK_ID, A.AUTHOR_NAME, DATE_FORMAT(B.PUBLISHED_DATE, '%Y-%m-%d') PUBLISHED_DATE
FROM (
      SELECT BOOK_ID, AUTHOR_ID, PUBLISHED_DATE
      FROM BOOK
      WHERE CATEGORY='경제'
     ) B JOIN AUTHOR A
ON B.AUTHOR_ID = A.AUTHOR_ID
ORDER BY PUBLISHED_DATE ASC;